name: Code Analysis

on:
    workflow_call:

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                actions:
                    -
                        name: 'Composer Validate'
                        run: composer validate

                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    #-
                    #    name: 'ECS'
                    #      run: composer check-cs
                    #      # todo add basic config

                    -
                        name: 'Active Classes'
                        run: |
                            composer require symplify/easy-ci:^11.2 --dev --ansi
                            vendor/bin/easy-ci check-active-class --ansi

        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: ramsey/composer-install@v2

            -   run: ${{ matrix.actions.run }}
