name: Code Analysis

on:
    workflow_call:

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan
                    -
                        name: 'ECS'
                        run: composer check-cs
                        # todo add basic config
                    -
                        name: 'Rector'
                        run: vendor/bin/rector process --dry-run --ansi
                        # todo add basic config - copy form ehere?
                    -
                        name: 'Active Classes'
                        run: |
                            composer require symplify/easy-ci:^10.0 --dev
                            vendor/bin/easy-ci check-active-class src --ansi
                            wget  
                            # todo add basic config

        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}