name: Rector

on:
    workflow_call:
        # see https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
        secrets:
            ACCESS_TOKEN:
                required: true

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    rector:
        # only on main repository, not on forks - see https://github.com/orgs/community/discussions/25641#discussioncomment-3248571
        if: github.repository == 'rectorphp/rector-phpunit' || github.repository == 'rectorphp/rector-symfony' || github.repository == 'rectorphp/rector-generator || github.repository == 'rectorphp/phpstan-rules || github.repository == 'rectorphp/rector-doctrine || github.repository == 'rectorphp/phpoffice || github.repository == 'rectorphp/rector-downgrade-php

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.GITHUB_TOKEN }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/rector process --ansi

            # tidy up code
            -   run: vendor/bin/ecs check --fix --ansi

            # todo add basic config - copy form ehere?

            # commit changes, see https://github.com/EndBug/add-and-commit
            -
                uses: EndBug/add-and-commit@v7.5.0
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: "[ci-review] Rector Rectify"
                    author_name: "GitHub Action"
                    author_email: "action@github.com"
                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
